### ISSUE TITLE
BUG REPORT: et doesn't shows mp4 files

### ISSUE THREAD

**Issue by mlunax** [solidiquis/erdtree#101]
My et doesn't shows mp4 files
Version: `erdtree 1.6.0`

```
❯ ls                                                                                      
'0001-FINAL [573011600].mp4'  '0003-FINAL [573012721].mp4'   lessons_links.txt
'0002-FINAL [573011998].mp4'  '0004-FINAL [573013069].mp4'   video_links.txt
❯ et                                                                                      
00-intro (709 B)
├─ video_links.txt (328 B)
└─ lessons_links.txt (381 B)
```

**Comment by solidiquis** [comment]
Interesting.. I am unable to reproduce this. What system are you on?
<img width="728" alt="Screen Shot 2023-03-29 at 9 22 22 AM" src="https://user-images.githubusercontent.com/45523555/228603971-78a2b162-6238-487d-9010-c1c9f521468d.png">

**Comment by mlunax** [comment]
My system:
`EndeavourOS Linux 6.2.8-arch1-1`
Yes, I have the `*.mp4`  in the .gitignore. 
It make sense now.
Thank you for explanation I thought that `--ignore-git-ignore` enabled by default
