### ISSUE TITLE
hang with non-existant directories?

### ISSUE THREAD

**Issue by ariSunz** [solidiquis/erdtree#106]
when given a directory that doesn't exist, erdtree seems to hang until it is terminated manually.

These are the last three lines displayed when running with `strace`:

```
getcwd("/home/arisun/Projects/andrea", 1024) = 29
readlink("/home/arisun/Projects/andrea/bogus", 0x7ffec44b6d50, 1023) = -1 ENOENT (No such file or directory)
futex(0x56497ab84a58, FUTEX_WAIT_BITSET_PRIVATE, 4294967295, NULL, FUTEX_BITSET_MATCH_ANY
```

I am running the latest release, 1.7.0 on Arch in case that matters

**Comment by solidiquis** [comment]
Thanks for catching this. Looks like accidentally allowed for an infinite loop when a non-existent directory is provided. I'll include a patch release tonight!

**Comment by solidiquis** [comment]
Actually just released it :]

**Comment by ariSunz** [comment]
I had to bit my tongue not to make a **_Blazingly Fast_** :tm: joke here

Works like a charm now, thanks!
