### ISSUE TITLE
Feature request: Add flags for providing owners and permission 

### ISSUE THREAD

**Issue by liketoeatcheese** [solidiquis/erdtree#108]
Hey mate,

First of all. BLAZINGLY FASTTTT

Into my request. It would be great if we could add some feature to view who owns the file and what permission it was granted. So basically showing rwx permission

**Comment by solidiquis** [comment]
Sure thing. Adding to my todo

**Comment by solidiquis** [comment]
Small update: this has just been merged into my work-in-progress v2.0 branch. If all goes well it should be out this Sunday or early next week: https://github.com/solidiquis/erdtree/pull/131

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131

**Comment by leberknecht** [comment]
Maybe im missing something here, but what are those flags?
