### ISSUE TITLE
Want to add the build-time Rust version to the README

### ISSUE THREAD

**Issue by lvzhenbo** [solidiquis/erdtree#125]
I encountered the following error when building version 1.8.1, and after checking the documentation and code, I realized that I needed the nightly version of Rust, but it was not specified in the README
![image](https://user-images.githubusercontent.com/32427677/231328449-586b98a7-e960-4071-aa46-8f43ff4ca1c1.png)

**Comment by solidiquis** [comment]
Ahh that's what I forgot to do my apologies! I'll get that added in later tonight.

**Comment by solidiquis** [comment]
Did you resolve this by installing nightly and then running `cargo +nightly install erdtree`?

**Comment by lvzhenbo** [comment]
For some reason I don't have `nightly-x86_64-pc-windows-msvc`, so I can't compile it for now, I have to use the compiled binaries

**Comment by solidiquis** [comment]
ah okay I'm sorry about that! I'll update the readme shortly
