### ISSUE TITLE
Asset for windows wasn't released in v1.8.1

### ISSUE THREAD

**Issue by suzuki-shunsuke** [solidiquis/erdtree#127]
The asset for windows wasn't released in v1.8.1.

https://github.com/solidiquis/erdtree/releases/tag/v1.8.1

<img width="972" alt="image" src="https://user-images.githubusercontent.com/13323303/231410766-4793b396-0803-4736-b29f-3ffc5633417e.png">

**Comment by solidiquis** [comment]
That is strange! I just added it. Thanks for pointing that out.
