### ISSUE TITLE
brew doctor warns about erdtree (1.8.1) not having an associated brew formula?

### ISSUE THREAD

**Issue by gbstan** [solidiquis/erdtree#128]
`brew doctor`
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  erdtree

**Comment by solidiquis** [comment]
Are you using an M1 mac by chance?

**Comment by gbstan** [comment]
Yes, I am. On 12 Apr 2023, at 17:37, Benji Nguyen ***@***.***> wrote:﻿
Are you using an M1 mac by chance?

**Comment by solidiquis** [comment]
@gbstan could I get the location of your `et` binary? 

`$ which et`

**Comment by gbstan** [comment]
Yes, sure. I am running homebrew via rosetta on my M1 mac:
```
which et
/usr/local/bin/et
```

**Comment by gbstan** [comment]
The warning from brew doctor has now disappeared.
Strange.

**Comment by solidiquis** [comment]
Great! I'm going to close the issue for now but feel free to re-open if you come across it again.

**Comment by joshmedeski** [comment]
I'm seeing the same error:

```
Warning: Some installed kegs have no formulae!
This means they were either deleted or installed manually.
You should find replacements for the following formulae:
  erdtree
```

I'm on a M1 mac, and when I run `which et` there is no output.
