### ISSUE TITLE
"Duplicate" hard links are skipped

### ISSUE THREAD

**Issue by FinnPerry** [solidiquis/erdtree#133]
If you have 2 or more files that are hard linked, erdtree will only display 1 of them.

e.g.
```
touch a
ln a b
et
```
will cause erdtree to output
```
mydirectory 
└─ b (0 B)
```

The issue also happens if the files are in different subdirectories.
e.g.
```
mkdir 1
mkdir 2
touch 1/a
ln 1/a 2/b
et
```
will cause erdtree to output
```
mydirectory 
├─ 1 
│  └─ a (0 B)
└─ 2
```

**Comment by FinnPerry** [comment]
Oh I just noticed it mentions this in the readme. Perhaps it could display them but not count towards the disk usage?

**Comment by solidiquis** [comment]
Yeah that's probably more sensible isn't it. I'll be sure to have a fix out for that in the next release :)

**Comment by solidiquis** [comment]
Just merged https://github.com/solidiquis/erdtree/pull/136 into my work-in-progress [v2.0 branch](https://github.com/solidiquis/erdtree/pull/131). If all goes well this will be included in the next release this Sunday :]

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131
