### ISSUE TITLE
Provide force color option

### ISSUE THREAD

**Issue by schnatterer** [solidiquis/erdtree#134]
I often pipe `tree` output to `aha`, in order to convert it to HTML and use it as rich text from there in presentations and articles (e.g. [this](https://cloudogu.github.io/gitops-talks/2023-03-mastering-gitops/#/ex2/8)). 

Piping leads to colorization being turned off, for `et`, too since #120.
So `tree` offers `-C` option.
```
 -C            Turn colorization on always.
```

I'd love to have the same for `erdtree`. Maybe as `--color`?

**Comment by solidiquis** [comment]
Sure thing, sounds sensible. I'll add it to my list of todos for the 2.0 release which hopefully will be out this Sunday if not sometime next week :)

**Comment by solidiquis** [comment]
Just merged https://github.com/solidiquis/erdtree/pull/135 into my work-in-progress [v2.0 branch](https://github.com/solidiquis/erdtree/pull/131). Hopefully will be out this Sunday!

**Comment by schnatterer** [comment]
🤩 Thank you very much. That was fast!

I'll post some insights on how I transform `et` output to HTML/SVG once 2.0 has landed here. Maybe it's interesting for some folks.

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131

**Comment by schnatterer** [comment]
BTW I finally open source my script for creating trees as SVG: https://github.com/schnatterer/tree2svg
It's a bit clumsy when it comes to converting devicons to SVG but maybe it's interesting for someone.

Thanks for `erdtree` :+1: :pray:
