### ISSUE TITLE
Orphaned reference to `et` in readme

### ISSUE THREAD

**Issue by steffenbusch** [solidiquis/erdtree#141]
First of all, thank you very much for creating, maintaining and continuous improving this remarkable tool!

After renaming the binary from `et` to `erd`, there is this orphaned reference to the old binary name:
https://github.com/solidiquis/erdtree/blob/master/README.md?plain=1#L473

```
$ et --completions zsh > ~/.oh-my-zsh/completions/_et
$ source ~/.zshrc
```

**Comment by solidiquis** [comment]
Thanks for catching this! Unfortunately `et` was still being used in completions command as well but I just fixed that and will release a minor patch later today.

https://github.com/solidiquis/erdtree/commit/a850e885f1aedaa037fb18b86a811f5ebe8d3154

**Comment by solidiquis** [comment]
I'm sorry I just woke up and totally did not see your PR.. apologies!
