### ISSUE TITLE
Completions still use "et" as executable name

### ISSUE THREAD

**Issue by ilyapopov** [solidiquis/erdtree#143]
See https://github.com/solidiquis/erdtree/blob/be7d52974131ed34f73d1df9fdbc0002019df999/src/main.rs#L63

**Comment by solidiquis** [comment]
Thanks! https://github.com/solidiquis/erdtree/commit/c4ff0dacb137f1007af27f692f1e5ee66bf47cb6

I'll release a patch for this later today.
