### ISSUE TITLE
Some of the images don't show up on crates.io

### ISSUE THREAD

**Issue by ilyapopov** [solidiquis/erdtree#145]
On crates.io page for erdtree https://crates.io/crates/erdtree , some of the images show up fine, but others don't. There is a message 'failed to load image' in place of these.

For example, ["Symlinks" section](https://crates.io/crates/erdtree#symlinks) looks like this:

![2023-04-26_16-51](https://user-images.githubusercontent.com/1054514/234614945-60f4d34e-d7e2-46f2-87eb-b2ff25aa81c3.png)

**Comment by solidiquis** [comment]
Screenshots back up with v3.0 :]
