### ISSUE TITLE
erdtree and symlinks with -l --long

### ISSUE THREAD

**Issue by alexjp** [solidiquis/erdtree#148]
Hi,

Thanks for the awesome project, very nice!

One issue I have seen, is that when using with -l (--long), it shows symlinks and its target, but the target does not have the full path!

So it is a bit misleading at to where the symlink actually points to.

Hope its clear, thank you very much!

**Comment by solidiquis** [comment]
Will have this fixed :)

**Comment by solidiquis** [comment]
Just closed! Let me know if you have any further feedback. WIll include in next release later this week.

**Comment by alexjp** [comment]
Thanks for fixing this, since I use symlinks a lot and for example in NixOS, symlinks are "everywhere" :P

Only feedback is its awesome :)
