### ISSUE TITLE
--dirs-first actually puts directories last

### ISSUE THREAD

**Issue by philer** [solidiquis/erdtree#149]
I'm honestly not sure if this is a bug or by design but to me the naming and behavior of the `--dirs-first` flag are exactly opposite. By any interpretation of the word "first" that I could think of `--dirs-first` puts the directories "last".
```
$ erd -L2 --dirs-first src
4096   B ┌─ main.rs
4096   B ├─ ansi.rs
4096   B ├─ utils.rs
24576  B ├─ icons.rs
4096   B │  ┌─ unix.rs
4096   B │  ├─ mod.rs
4096   B │  ├─ windows.rs
12288  B ├─ tty
4096   B │  ┌─ xattr.rs
4096   B │  ├─ inode.rs
4096   B │  ├─ mod.rs
24576  B │  ├─ permissions
36864  B ├─ fs
4096   B │  ┌─ mod.rs
16384  B │  ├─ styles
16384  B │  ├─ disk_usage
45056  B │  ├─ context
69632  B │  ├─ tree
151552 B ├─ render
237568 B src
```
Files got printed "first", files are the "first" thing I read, top to bottom.

Meanwhile when adding `--inverted` it does exactly what I would have expected it to do without `--inverted` (well, except for the reverse sorting), including putting the dir name _above_ its content. This is by far the most common way for directory trees to be displayed, both by GUIs (e.g. IDE side bars) as well as commands like `tree` and `find`.

So, in my humble opinion, either the flag should do the opposite or be renamed to `--dirs-last`or `--files-first` or maybe `--files-above`. Personally I'd prefer the behavior to change, rather than the name.

Either way, this is a wonderful tool. Thank you!

edit: I'm running the freshly downloaded 2.0.0 binary.

**Comment by solidiquis** [comment]
Yeah that was poor judgment on my part. I'll follow through with your suggestion and have it switched while also providing a `--dirs-last` option which does what `--dirs-first`currently does. Thanks for the input!

**Comment by solidiquis** [comment]
Just closed! Feel free to let me know if you have any further input. Will be included in next release sometime this week :]
