### ISSUE TITLE
text output takes very long

### ISSUE THREAD

**Issue by kakulukia** [solidiquis/erdtree#153]
Hi,

i just found this tool and immediately wanted to try it out, but firing up `erd` nothing happened, weird!

92451 directories, 639026 files, 14270 links
 ~  took 2m11s

My shell displays runtimes for longer running commands - turns out erd took quite some time scanning the system. It should have told me that the index was missing or whatever it was doing in the mean time. I understand it did a lot, but a command taking longer than say 2s without anything happening, makes me think its broken. :(

92451 directories, 639098 files, 14270 links
 ~  took 45s

Same directory: The second run was much quicker, **BUT** it was even starting to draw output on the screen after just about 10s seconds. So the other 35s it took to output my directory structure. Insane!

`erd --long --human --level 1` will be done after the the mentioned 10s as the output is very tiny.

Comparing to du: `du -d 1 -h | sort -h` 26s vs. `erd` 2m11s

du wins depending on the amount of text drawn on screen, but even with the level 1 option red (with index) ist just 50% better

erd is a little bit faster than dust and also about 20% faster than `broot --sort-by-size`, but broot will display instantly and have sizes popping in after a few seconds. Sure different tool with different purpose. But I bet there is a lot potential left for erd.

I would go as far as calling it a replacement for ls, tho. :/

**Comment by solidiquis** [comment]
Thanks for the feedback! What I'm taking away from this is the following:

- There should be some sort of progress indicator for these large traversals informing the user that files are currently being retrieved from disk.
- Once files are retrieved from disk and the render is being computed, assuming it's a very large output that takes time, `erdtree` should probably periodically flush a portion of the output each time until the full render has been printed.

Anything I'm missing? Let me know your thoughts :)

**Comment by kakulukia** [comment]
Sounds good to me! I bet the flushing will be a lot faster than directly printing to screen.

**Comment by solidiquis** [comment]
Addressed by 1eef4b580107349cee3dfd8087625058e83c9ffd
