### ISSUE TITLE
Sort by timestamp feature

### ISSUE THREAD

**Issue by Vollbrecht** [solidiquis/erdtree#158]
You already support sort by name and by size, it would be nice addition if one could also sort by the timestamp (metadata timestamp from -long option)

Thanks for the great tool!

**Comment by solidiquis** [comment]
adding to Todo! Thanks for the suggestion!

**Comment by solidiquis** [comment]
Closed by https://github.com/solidiquis/erdtree/pull/175

**Comment by Vollbrecht** [comment]
ty ;) will test it out
