### ISSUE TITLE
Feature Request: Sort by Access/Modification/Creation Time

### ISSUE THREAD

**Issue by ImmanuelHaffner** [solidiquis/erdtree#173]
I love `erdtree` already! To fully replace `ls` in my day-to-day use, I would need it to sort the output by time rather than file size. Sorting by time should still respect `--dirs-first`.

**Comment by solidiquis** [comment]
On its way in v3.0! Hopefully out this weekend :)

**Comment by ImmanuelHaffner** [comment]
Whoa, that was a fast reply! Great, I'm looking forward to the release. Keep up the great work, it's appreciated ;)
