### ISSUE TITLE
Icons update

### ISSUE THREAD

**Issue by fcs-ts** [solidiquis/erdtree#191]
Icons stopped working for me (I use wezterm , which bundles nerdfonts) and it seems it is because of this https://github.com/ryanoasis/nerd-fonts/issues/1190

**Comment by solidiquis** [comment]
Hey @fcs-ts could you confirm if the latest fix works for you?

**Comment by pitbuster** [comment]
@solidiquis: @fcs-ts is my work account, so I can confirm :sweat_smile:

**Comment by solidiquis** [comment]
Dude that's hilarious LOL.. I'll out out a patch release today.. thanks!
