### ISSUE TITLE
NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [solidiquis/erdtree#195]
FYI, I had to revert our package to 3.0.1, https://mail-index.netbsd.org/pkgsrc-changes/2023/06/15/msg276933.html

It builds fine on my machine but it can't be merged into main where Rust-1.69 is the current version available.
Regards

**Comment by solidiquis** [comment]
Thanks for the heads up! I guess we'll have to wait until main gets the latest 1.70

**Comment by 0323pin** [comment]
Yes, we need to wait for 1.70

It won't happen for at least two weeks, maybe three. We are soon cutting the stable branch and there's a commit freeze coming-up.

Nothing I can do.
Closing this issue now.
