### ISSUE TITLE
off topic question for used font in your screenshots

### ISSUE THREAD

**Issue by anolting** [solidiquis/erdtree#196]
Hi

I would like to ask for the font you are using in your shell. Specifically which character represents the cocktail glass in your PS1?

Best Alex

**Comment by solidiquis** [comment]
[Font](https://github.com/solidiquis/dotfiles/blob/9a33aa450666c6ef474a8316537e6b166670669e/wezterm/font.lua#L9) | [PS1](https://github.com/solidiquis/dotfiles/blob/9a33aa450666c6ef474a8316537e6b166670669e/zsh/env.zsh#LL11C24-L11C29)

And that is not a cocktail glass; it's [boba tea](https://www.i2symbol.com/symbols/drinks/x1F9CB-bubble-tea-drinks-symbol-smiley-face?l=ar) :]
