### ISSUE TITLE
`erd -p doesnotexist` deadlocks, rejects `^C`, and doesn't properly restore terminal

### ISSUE THREAD

**Issue by vincentdephily** [solidiquis/erdtree#214]
Running `erd -p doesnotexist` anywhere prints `Preparing output...` and then just sits there forever, consuming no CPU. It also doesn't exit on a `^C`. This can be worked around with a `^Z` followed by a `kill %1` but this leaves the terminal in a "cursor not visible" state, requiring an extra `reset` to get back to normal.

Running `erg -p doesnotexist --no-progress` immediately prints `No entries to show with given arguments.` and exits.

Expected:
 * `erd -p doesnotexist` should exit immediately.
 * Hitting `^C` at any point during `erd` execution should work, and restore terminal settings.

**Comment by solidiquis** [comment]
Thanks for catching this. Shipping a patch immediately.

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/releases/tag/v3.1.1
