### ISSUE TITLE
Windows: '--config' was specified but a `.erdtree.toml` file could not be found

### ISSUE THREAD

**Issue by adam-frisby** [solidiquis/erdtree#217]
I placed a .erdtree.toml file in %APPDATA%\erdtree\, but erd does not seem to find it.

https://github.com/solidiquis/erdtree/blob/ccdb8184232468551e82eacc98857d3393a6d966/src/context/config/toml/mod.rs#L218C29-L218C41

Should that line read `strip_suffix` rather than `strip_prefix`?

**Comment by solidiquis** [comment]
Damn.. yes it should be strip prefix. Would you like to make a contribution or would you like me to fix it? Once it's merged in I'll make another patch release immediately! It is late for though so I wouldn't be able to get to it at least for the next 10 hours or so.
