### ISSUE TITLE
erdtree v3.1.2 macOS panic: possibly due to dirs with large-number files + less(1) piping?

### ISSUE THREAD

**Issue by johnnyutahh** [solidiquis/erdtree#223]
`erdtree` v3.1.2 panics on the `rust`-repo dir, but not the `erdtree`-repo dir, when piping through `less` and then type `q` after the first "page" (if that doesn't make sense, I can further clarify upon request). Details:

https://gist.github.com/johnnyutahh/974f6dfca0c43c1ca4c2c06faeaaae87

I've seen backtraces in this context (I think?) in previous `erdtree` versions, but this is the first time I attempted to collect the details. I'm also not sure if this is a known issue or FAQ or some such, so apologies if this is a "duplicate" topic/issue.

**Comment by solidiquis** [comment]
Thanks! I will investigate.
