### ISSUE TITLE
Potential name clash

### ISSUE THREAD

**Issue by glitsj16** [solidiquis/erdtree#23]
https://github.com/solidiquis/erdtree/blob/89bd048e7416c95b29b483de9f69b2e986f8e2c1/README.md?plain=1#L145

Hi, I noticed [erdtree](https://aur.archlinux.org/packages/erdtree) is in the AUR and I installed it. Works very well, congrats!

As long-time user and collaborator to the [Firejail](https://github.com/netblue30/firejail) project it didn't take long before creating a firejail profile for erdtree. That profile also works quite well, but then I hit a snag. Apparently the spreadsheet component of [WPS Office](http://wps-community.org/) is also called (and installed as) `et`.

Obviously that's not a problem for the erdtree dev(s) as such. I sure like short, easy to remember command names myself. Realizing what a name change of the binary entails, I don't want to suggest to do so. I just wanted to bring this to your attention.

**Comment by wuyudi** [comment]
now here is [erdtree-bin](https://aur.archlinux.org/packages/erdtree-bin).For those who don't want to compile.

**Comment by solidiquis** [comment]
Thank you for bringing this to my attention! Before I decide on changing the name of the binary to something else what's the best way for me to go about ensuring that the next name I choose won't result in a similar issue?

**Comment by glitsj16** [comment]
> ... what's the best way for me to go about ensuring that the next name I choose won't result in a similar issue?

Good question. FWIW, I happened to stumble on the `et` vs `erdtree` name clash by sheer coincidence. I'm also not a professional in any sense of the term, just a Linux hobbyist with enough free time on hands to delve around all sorts of places.

Sadly I'm not aware of any single resource to check for existing binary names. That being said, most if not all Linux distributions do offer package search facilities. Usually these include package content links, so it's fairly easy to at least check these resources to see under what name a binary already ended up in /bin, /sbin, /usr/bin, etcetera.

A short list of examples:

- Arch Linux (https://archlinux.org/packages/)
- AUR (https://aur.archlinux.org/packages)
- Debian (https://www.debian.org/distrib/packages)
- Fedora (https://src.fedoraproject.org/)
- Ubuntu (https://packages.ubuntu.com/)

One site I particularly find very informative is [repology](https://repology.org/).

Depending on the amount of time one has/wants to invest in this kind of research I'd suggest doing a quick search on major dev hubs like GitHub, Gitlab, etc. Who knows, with the latest outpour of AI GPT search apps left, right & center you might just track one of those too :)

**Comment by dljsjr** [comment]
This also collides with [Eternal Terminal](https://eternalterminal.dev/), an SSH remote terminal alternative kinda like `mosh`.

**Comment by solidiquis** [comment]
Version 2.0 is looming in the horizon as I plan to make a lot of breaking changes (probably middle to late April). I will likely change the name of the compiled binary then with its release.

**Comment by solidiquis** [comment]
@dljsjr "erd" really is the only other sensible alternative lol. I'll probably go with that. Thanks for the suggestion!

**Comment by blinxen** [comment]
`et` also has a name clash in fedora --> https://packages.fedoraproject.org/pkgs/et/et/

Wanted to add this for completeness. `erd` on the other hand has no name clashes in fedora.
Once you change the binary name, I will package `erdtree` for fedora.

**Comment by solidiquis** [comment]
Thanks @blinxen! Hoping to get that done sometime next week.

**Comment by solidiquis** [comment]
Small update: Now that v1.8.0 out I'm going to get started on `v2.0.0` which will have quite a few breaking changes. `v2.0.0` will have its compiled binary changed to `erd`.

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131
