### ISSUE TITLE
Donation for erdtree

### ISSUE THREAD

**Issue by WMACCESS** [solidiquis/erdtree#232]
Dear Benji,

We would like to show our appreciation and support by making a small financial donation towards the further development and maintenance of `erdtree`.
**Could you please provide us with your PayPal account email address or any other preferred payment method so that we can transfer the funds?**

We believe that open source software is essential for innovation, and we are committed to supporting projects like `erdtree` that make a real difference in the world. 
You can read about our Open Source support initiative for this year in our GitHub Account (https://github.com/WMACCESS).

Thank you for your outstanding work on `erdtree`, and we look forward to hearing from you soon.

Best regards,

The WMACCESS Team of CPB Software
Anna Valls Ferron

**Comment by solidiquis** [comment]
@WMACCESS Got it!

What you folks are doing is incredibly admirable. Even though us FOSS authors/maintainers do what we do for free as a labor of love, it is always deeply appreciated when people provide a bit of financial support for the time we spend on these passion projects which aim to help others. It is also intensely motivating! Again you folks are incredibly. I'm very grateful. Cheers!
