### ISSUE TITLE
If just it as the study project , what can I get from this projects.

### ISSUE THREAD

**Issue by csh0101** [solidiquis/erdtree#247]
I ''m noob at rust and terminal software development. Can you explain to me, what can I get from this project~

**Comment by leberknecht** [comment]
No offense, but thats really not a question you should open an issue for. Only you can answer that :) Read the source, see what you can get from it. 

..but i would guess that you would learn a bit about file-system low-levels (well...lower-than-usual-but-not-"driver-level-low")

**Comment by csh0101** [comment]
> No offense, but thats really not a question you should open an issue for. Only you can answer that :) Read the source, see what you can get from it.没有冒犯，但这真的不是你应该提出的问题。只有你能回答这个问题:)阅读源代码，看看你能从中得到什么。
> 
> ..but i would guess that you would learn a bit about file-system low-levels (well...lower-than-usual-but-not-"driver-level-low")..但我猜你会学到一些关于文件系统低级的知识（嗯......低于平时，但不是“驾驶员级别低”）

yep, you are right . I think I should see the source code. I will colse it
