### ISSUE TITLE
[feature] binary prefixes

### ISSUE THREAD

**Issue by scarf005** [solidiquis/erdtree#29]
hello, thank you for making this program. i think it'd be a good idea for erdtree to support binary prefix, since other programs like du uses binary prefix as default like following:

```
 $ du --help
...
 --si              like -h, but use powers of 1000 not 1024
```

> As recommended in [IEC 80000-13](https://en.wikipedia.org/wiki/ISO/IEC_80000#cite_note-80000-13:2008-14), this command will report sizes using SI units rather than binary units.

also, could you point me in the direction of source where it states SI unit is preferred over binary units?

> Definition of prefixes using powers of 10—in which 1 kilobyte (symbol kB) is defined to equal 1,000 bytes—is recommended by the [International Electrotechnical Commission](https://en.wikipedia.org/wiki/International_Electrotechnical_Commission) (IEC)

i found relevent paragraph in [byte](https://en.wikipedia.org/wiki/Byte#Units_based_on_powers_of_10), and it looks like it's for SI prefix using 1000 vs 1024, not that it's preferred to use SI unit over binary prefix.

**Comment by solidiquis** [comment]
Thank you for the input. I will add support for this today and include it in the next minor version release. Do you have any thoughts on which one should be the default (SI vs. Binary prefix)? I've gotten enough asks at this point to seriously consider having binary prefixes be the default.

**Comment by scarf005** [comment]
thank you. i think using binary prefixes as default would be a good idea to match up with du.

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/commit/b118006640a53e8083977d393beb1eca1c239e15

Binary units have now replaced SI units. Will update README and include in next minor version bump in next few hours!
