### ISSUE TITLE
Sort by filesize could be a good feature

### ISSUE THREAD

**Issue by andyyehoo** [solidiquis/erdtree#3]
The performance of this tools is great! Amazing~

If a sort option for this command can be added. It would be better. In many cases, we might want to find the largest file or directory. Sort function can save the time for users to check from top to button.

For example:
------------------------

OPTIONS:

……
-s:  Sorted by file size

**Comment by solidiquis** [comment]
Sure thing! I'll take a look into adding in some sort functionality this weekend.

**Comment by solidiquis** [comment]
Alright, added an option to sort by memory size. Example:

Ascending:
```
$ erdtree -s asc
```

Descending:
```
$ erdtree -s desc
```

I've made some other additional changes as well. Please checkout the README for more info :]

Relevant commit: 8ef09b6705522a56b3601ef70f51bb861c599b23

Let me know if there are any problems!
