### ISSUE TITLE
[feature] Add `args_override_self(true)`

### ISSUE THREAD

**Issue by bryceberger** [solidiquis/erdtree#34]
Reasoning: I would like to make an alias to change some default behavior (sort, prefixes (future), etc). However, supplying the same argument twice (`et -s name -s size`) is an error.

Current behavior: `et -s name -s size` will not execute, with the message (from `clap`) that `--sort` cannot be used multiple times.
Expected behavior: `et -s name -s size` will execute, and sort output by size.

(This is a 3 line change and I have a PR ready, just wanted approval first as stated in the readme)

**Comment by solidiquis** [comment]
Feel free to submit the PR!

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/35
