### ISSUE TITLE
[feature] Sort directories first

### ISSUE THREAD

**Issue by bryceberger** [solidiquis/erdtree#37]
À la `tree --dirsfirst`, an option to sort directories above normal files.

In my view, there are two ways to implement this:
- `et --sort dir`, a manually-implemented "sort by directory"
- `et --sort ... --dirs-first`, an option for all sorting methods to sort directories first

I have both implemented, don't know which (if either) to make a pr for.

**Comment by bryceberger** [comment]
Probably should have left a link to see how I have them implemented

- [`et --sort dir`](https://github.com/bryceberger/erdtree/tree/dir-sorting-fn)
- [`et --sort ... --dirst-first](https://github.com/bryceberger/erdtree/tree/dir-sorting-option)

**Comment by solidiquis** [comment]
Hey @bryceberger because you're now officially a contributor feel free to just make PRs. I'll make note of the fact that existing contributors don't need to ask for permission going forward. But this sounds great!

**Comment by bryceberger** [comment]
Alright. I prefer the second (switch for all algorithms) implementation, so I'll open a PR for that.
