### ISSUE TITLE
`--ignore-git` doesn't seem to work

### ISSUE THREAD

**Issue by BWStearns** [solidiquis/erdtree#45]
running et with hidden files and ignore git doesn't seem to work. I looked into it but I couldn't track it down fully yet (I'm still trying to grok `OverrideBuilder` atm).

```
[bws:~/circadian_tools] avgday(+19/-0)+ ± et -H --ignore-git
circadian_tools (220.02 KB)
├─ src (6.18 KB)
│  ├─ chrono.rs (2.01 KB)
│  └─ lib.rs (4.18 KB)
├─ .git (197.54 KB)
│  ├─ FETCH_HEAD (96.00 B)
│  ├─ packed-refs (112.00 B)
│  ├─ refs (809.00 B)
│  │  ├─ remotes (399.00 B)
│  │  │  └─ origin (399.00 B)
│  │  │     ├─ tau (41.00 B)
│  │  │     ├─ main (41.00 B)
```

Maybe this code here is getting called before the show-hidden-glob gets added so it basically gets overwritten?

```
if self.ignore_git {
    builder.add("!.git/**/*")?;
}
```

**Comment by solidiquis** [comment]
Ahh thanks for catching this. Unfortunately it's a work week for me so I won't be able to get to this until the end of the week or the weekend, but if you're interested in tackling this let me know :)

**Comment by BWStearns** [comment]
No problem. I’ll take a swing at it this afternoon.

**Comment by solidiquis** [comment]
Got to it :]

**Comment by BWStearns** [comment]
Awesome. Sorry I didn't get to it, caught the layoff virus going around and been interviewing a bunch.

**Comment by solidiquis** [comment]
@BWStearns ahhh homie I'm sorry to hear. No worries at all. Wishing you the best of luck. It's rough out there.
