### ISSUE TITLE
Does erdtree have a configuration file or environment variable?

### ISSUE THREAD

**Issue by mathomp4** [solidiquis/erdtree#48]
I'm getting used to erdtree and liking what I'm seeing. I usually run it as `et --icons` or `et --icons --dirs-first`, etc.

So now I'm wondering: Is there some file or variable I can set that sets the "default" options for `et`? That is, `export ERDTREE=--icons ...` or an `.erdtreerc` or `.config/erdtree.toml` or such file where I could put in my "always show icons" options?

I know I can make an alias, but, well, if there's a more "canonical" way of doing this, I'd prefer that.

**Comment by solidiquis** [comment]
There isn't at the moment but I can implement this sometime towards the end of the work week or during the weekend. o you have any suggestions on the form this should take?

Reading in an environment variable or configs and having that be the default set of args/opts passed to `et` might be a tad annoying because there might be some cases wherein you'd want to adjust the arguments.

How do you feel about `-c, --config` when wanting to run `et` with a config file`?

**Comment by mathomp4** [comment]
@solidiquis I'd probably prefer a config file. I mean, The `ERDTREE` is like `LESS` for less, but the advantage of a file is that you can have comments, which is nice, and it's simple to put in dotfile repos. 

For example, `ripgrep` uses an [environment variable to point to the file](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file) which is one way forward.

Other software like `chezmoi` (which I use to manage my dotfiles) just say, ["we look for `~/.config/chezmoi/chezmoi.toml`"](https://www.chezmoi.io/user-guide/setup/#understand-chezmois-files-and-directories) and that's where you put stuff!

I suppose if Rust programs have a "convention" that's the way to do it, but I'm flexible.

**Comment by solidiquis** [comment]
Thanks @mathomp4. I'll checkout what `ripgrep` and `chezmoi` is doing and do something in the same vain. Since it's a work week I'll probably get it out sometime during the weekend and include it in the next minor version bump. Thank you for the feedback!

**Comment by mathomp4** [comment]
@solidiquis No big rush. I'm still learning your code anyway! Probably take me a few weeks to settle on the settings I like 😄

**Comment by solidiquis** [comment]
Just merged in https://github.com/solidiquis/erdtree/pull/52 which adds support for a config file very similar to how `ripgrep` does it.

Checkout [this section](https://github.com/solidiquis/erdtree#configuration-file) of the README to read up on how to set that up. I'll be including this in the next minor release some time tomorrow (Sunday) so keep an eye out :]

**Comment by mathomp4** [comment]
> Just merged in #52 which adds support for a config file very similar to how `ripgrep` does it.
> 
> Checkout [this section](https://github.com/solidiquis/erdtree#configuration-file) of the README to read up on how to set that up. I'll be including this in the next minor release some time tomorrow (Sunday) so keep an eye out :]

Thanks! I'll keep an eye out for brew updating it!

**Comment by solidiquis** [comment]
@mathomp4 just fyi I just threw up a [PR to get v1.4.0 on homebrew-core](https://github.com/Homebrew/homebrew-core/pull/125498). Once that's up you should be good to update via brew :]

**Comment by mathomp4** [comment]
Took me a few days to get to this, but it works perfectly!

(Well, I got confused as I had v1.5.2 and I was wondering if I had the wrong erdtree. Nope! Just fast versions! 😄 )

**Comment by solidiquis** [comment]
@mathomp4 you came at the right time! `v1.4.0` was actually quite buggy, but just FYI, `-l, --level` doesn't currently work in the config file for `v1.5.2`; I just resolved that issue this morning so be sure to check back early next week (Monday) if you want a newer release with that issue resolved :]
