### ISSUE TITLE
[Feature request:] Pruning (when filtering using glob, don't print the empty branches)

### ISSUE THREAD

**Issue by TomLebeda** [solidiquis/erdtree#53]
I really like erdtree, here is little idea that I came across while using erdtree to search for files on my disk.

As the title says, it would be useful to enable "pruning" so the output only contains branches that aren't empty at the end. 

Example: 
let's say we have directory:
```
 folder_a
├─  folder_b
│  ├─  file_d (0.00 B)
│  ├─  file_c (0.00 B)
│  ├─  folder_ba
│  │  └─  file_x (0.00 B)
│  ├─  folder_bc
│  │  └─  file_z (0.00 B)
│  └─  folder_bb
│     └─  file_y (0.00 B)
├─  file_a (0.00 B)
├─  folder_c
│  ├─  file_ab (0.00 B)
│  ├─  file_ac (0.00 B)
│  ├─  file_ad (0.00 B)
│  ├─  file_f (0.00 B)
│  └─  file_e (0.00 B)
└─  file_b (0.00 B)


```
and I want to filter for files that contains "a": `et -g "file_*a*"` and the output is:
```
 folder_a
├─  folder_b
│  ├─  folder_bc
│  ├─  folder_ba
│  └─  folder_bb
├─  file_a (0.00 B)
└─  folder_c
   ├─  file_ab (0.00 B)
   ├─  file_ac (0.00 B)
   └─  file_ad (0.00 B)
```
but with the "pruning" enabled, it would skip the "dead-ends" and print just:
```
 folder_a
├─  file_a (0.00 B)
└─  folder_c
   ├─  file_ab (0.00 B)
   ├─  file_ac (0.00 B)
   └─  file_ad (0.00 B)
```
The idea is that when searching through bigger trees, the dead-ends are cluttering the output.

**Comment by solidiquis** [comment]
Sure thing; this doesn't sound too hard to implement. I'll be sure to include this in the next minor release before Monday :)

**Comment by solidiquis** [comment]
Will be included in next minor release later today :]
