### ISSUE TITLE
[FEATURE] use `-L` flag for level

### ISSUE THREAD

**Issue by futuretech6** [solidiquis/erdtree#56]
In tree, `-L` is used for specifying the depth of the tree. Currently `-L` flag is not used by et, so can et use both `-L` and `-l` for the level to match the convention?

**Comment by solidiquis** [comment]
Small update: this has just been merged into my work-in-progress v2.0 branch. If all goes well it should be out this Sunday or early next week: https://github.com/solidiquis/erdtree/pull/131

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131
