### ISSUE TITLE
[Feature request] Displaying modification time

### ISSUE THREAD

**Issue by ClementNerma** [solidiquis/erdtree#62]
Hi!

I've been using erdtree for a bit of time now and I'm quite happy with it, thanks for making this tool :)

I have one request though: would it possible (don't if it is) to add an option to also display the modification time of elements? It'd very, very useful for me.

Currently I use `fd ... -x ls -lhd` but it is quite slow, especially compared to `erdtree`.

**Comment by solidiquis** [comment]
Hello! As it's a work week I won't be able to put too much thought into how I would go about this, but let me think about it and I'll get back to you later towards the weekend :]

I think the tricky part mainly thinking about how it would look printed.

**Comment by solidiquis** [comment]
Small update: this has just been merged into my work-in-progress v2.0 branch. If all goes well it should be out this Sunday or early next week: https://github.com/solidiquis/erdtree/pull/131

**Comment by solidiquis** [comment]
https://github.com/solidiquis/erdtree/pull/131
