### ISSUE TITLE
fix config locations 

### ISSUE THREAD

**Issue by omaru-ok** [solidiquis/erdtree#64]
i still do not understand what is the point of making **_$HOME_** more clutter to maintain, even when we try to make it _Clean / Neat_ 

issue is regarding [config-location](https://github.com/solidiquis/erdtree#configuration-file)
- `$HOME/.erdtreerc`
make location good , i mean standards of unix as `.config/et/.etrc'

some work around or **_TIPS_** which i have been using to tackle it
in **Window** (coz i use it for now ) :( 
in **$profile** put this 
`$env:ERDTREE_CONFIG_PATH="path/to/conf/"`

in **Unix** 
in `.bashrc` put
`export ERDTREE_CONFIG_PATH=path`

**Comment by solidiquis** [comment]
Yup I made an issue for this here https://github.com/solidiquis/erdtree/issues/63

I will make this change in the next minor release before monday.

**Comment by solidiquis** [comment]
Let me know if you have any further issues :]
