### ISSUE TITLE
`--dirs-first` flag does nothing if no SortType is specified

### ISSUE THREAD

**Issue by fawni** [solidiquis/erdtree#65]
for example: `et --dirs-first` will not sort directories above files, but if sort type is specified: `et --dirs-first -s name` it works as expected.

i was able to produce the expected behavior by adding a `None` enum variant to `SortType` and adding:

```rs
} else if ctx.dirs_first() {
	Order::from((SortType::None, true))
		.comparator()
		.map(|func| current_node.sort_children(func));
}
```

[to this line](https://github.com/solidiquis/erdtree/blob/bc70dd86833131112b923d25de285994f388fdb2/src/render/tree/mod.rs#L175), but there are probably "cleaner" approaches.

also, i noticed that clippy suggests a bunch of stylistic refactors all over. do you have an opinion against such stylistic approaches?

**Comment by solidiquis** [comment]
I do not, but if you plan to open a PR if you could pass on running `clippy` that'd be awesome. Someone has another PR that's currently waiting to be merged and they ran `clippy` and I'd be worried about really gnarly merge conflicts that could cause headaches. Thanks for looking into this btw!
