### ISSUE TITLE
Strange coloring issue on Windows Terminal + MSys2

### ISSUE THREAD

**Issue by cbeust** [solidiquis/erdtree#66]
The naked command issues the ANSI codes but they are not being processed. However, piping it through `cat` works:

![image](https://user-images.githubusercontent.com/92322/224850825-19890aac-7f6c-4646-9307-cd727688e8ac.png)

Windows 10, MSys2, Windows Terminal.

**Comment by solidiquis** [comment]
Thank you I'll look into this and have a fix for it soon. Will include in next minor release end of week

**Comment by cbeust** [comment]
Oh, I am dying to hear what the problem is, I'm still trying to puzzle it out, browsing your code and tweaking my environment.

What is causing this?

**Comment by solidiquis** [comment]
I haven't done enough digging to know exactly but I assume the answer is likely found here https://github.com/msys2/MSYS2-packages/issues/1494

**Comment by fawni** [comment]
this can be solved by enabling virtual terminal for windows

luckily erdtree uses `ansi_term` which has a convenient function for that:

```rs
ansi_term::enable_ansi_support()
```

([source code](https://github.com/ogham/rust-ansi-term/blob/ff7eba98d55ad609c7fcc8c7bb0859b37c7545cc/src/windows.rs))

**Comment by cbeust** [comment]
Thanks @solidiquis, look forward to trying it and closing this issue :)

**Comment by cbeust** [comment]
I confirm the issue is fixed! I pulled and rebuilt, and...

![image](https://user-images.githubusercontent.com/92322/226389093-48fb0331-3106-459b-9d38-287a5c8ffbc8.png)

Thank you!
