### ISSUE TITLE
`--ignore-git-ignore` in erdtreerc is ignored

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [solidiquis/erdtree#71]
To reproduce, put `--ignore-git-ignore` in `$HOME/.erdtreerc`.

Then run `et` from a directory that has some gitignored files. They won't be printed.

For comparison, if the flag is supplied through command line: `et --ignore-git-ignore`, it works as expected.

```
> et --version
erdtree 1.4.1
```

**Comment by solidiquis** [comment]
Thank you the issue should be resolved. I'll do a minor release tonight :]
