### ISSUE TITLE
[feature] Add support for generating shell completions

### ISSUE THREAD

**Issue by Brezak** [solidiquis/erdtree#79]
There are 2 ways this could be done:

- A build script like [dust](https://github.com/bootandy/dust/blob/master/build.rs) does it
- A flag similar to how [mdBook](https://github.com/rust-lang/mdBook/blob/master/src/main.rs#L78-L85) does it

I've tried to implement both solutions and the build script solution would require changing how imports are done since just [including](https://github.com/rust-lang/mdBook/blob/master/src/main.rs#L78-L85) the context module essentially means [having to include almost the entire project module hierarchy](https://github.com/Brezak/erdtree/blob/5eb9266a992c397db84feee68c26460e224fca9b/build.rs#L6-L63).

**Comment by solidiquis** [comment]
Thanks @Brezak for tackling this! I'll do my best to take a look at this and give you my thoughts sometime tonight or tomorrow :]

**Comment by Brezak** [comment]
Should have mentioned this but I've also made an attempt at [implementing the flag approach](https://github.com/Brezak/erdtree/commit/cfbf77d7a047095b5ba04f4d2a93106096cc3afe) if you wanna take a look at how it could work.

**Comment by solidiquis** [comment]
@Brezak I do like the flag approach as it feels far less awkward in my opinion. Not a huge fan of the duplicate code in the `build.rs` as it can be painful for people knowing that they need to sync up changes between that and `main.rs`, `utils.rs` etc.. Let me know your thoughts. Feel free to whip up a PR!
