### ISSUE TITLE
Feature idea: folders only

### ISSUE THREAD

**Issue by aldanor** [solidiquis/erdtree#84]
Use case: you have a small number (dozens) of folders, each of which may contain thousands of files. They may be at different depths, e.g.
```
a/{1k files}
a/b/{1k files}
b/c/d/{1k files}
```
in which case you might want a report like
```
├─ a (123.45 MiB)
│  ├─ b (67.89 MiB)
├─ b (234.56 MiB)
│  ├─ c (56.78 MiB)
│  ├─ ├─ d (8.90 MiB)
```

For cases like this, would be real nice to have "dirs only" flags (e.g. `-D / --dirs-only`).

Apologies in advance if this is already doable and I have missed it.

**Comment by bryceberger** [comment]
This is *somewhat* possible already, via something like `et -g "."`. Assuming you don't have `-P` set, it will print out all directories (and no files, assuming you didn't do some magic to get a file named just "`.`"). However, this doesn't print any size information.

**Comment by aldanor** [comment]
> However, this doesn't print any size information.

Well, that's the main point here, listing directory sizes but not the specific files inside them 🙂 (due to the sheer number of files and a small number of directories)

**Comment by solidiquis** [comment]
At face value this seems trivial to implement and seems useful. I'm not sure off the top of my head if there are other considerations to be made about how this might play with other options, but instinctually I feel as though there wouldn't be any conflicts. Any thoughts @bryceberger ?
